[package]
name        = "fragcap-cli"
description = "Command line interface for fragcap."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
readme                 = "README.md"
categories             = ["command-line-utilities", "network-programming"]

[dependencies]
fragcap.workspace = true
[[bin]]
name = "fragcap"
path = "src/main.rs"
