[package]
name        = "fragcap-attr"
description = "Flow attribution and process watching."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
fragcap-core.workspace = true
