[package]
name        = "fragcap-sink"
description = "Output sinks and transports."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true
homepage.workspace     = true
keywords.workspace     = true
categories.workspace   = true
readme                 = "README.md"

[dependencies]
fragcap-core.workspace = true
