[package]
name        = "fragcap-capture"
description = "Packet acquisition backends."
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
fragcap-core.workspace = true
