// SPDX-License-Identifier: Apache-2.0

//! A hand-rolled parser for Steam's binary application-info cache
//! (`appcache/appinfo.vdf`).
//!
//! This is a different format from the text VDF that [`crate::vdf`] reads:
//! `appinfo.vdf` is a length-prefixed binary key-values file that Steam writes
//! for every application it has fetched metadata for, keyed by application id and
//! carrying, per application, a change-number and a launch configuration. Reading
//! it needs no Steam session, no credential, and no network: it is a file Steam
//! already wrote, so this parser is passive and P-1 clean, like the manifest
//! reader beside it.
//!
//! The parser reuses [`crate::vdf::VdfValue`] as the parsed tree, so navigating an
//! app's `config/launch` reads the same way the text parser's output does. Each
//! app section is framed by a size field, so a malformed section is isolated: it
//! is reported as a failure and the walk resyncs to the next section rather than
//! losing the whole file (FR-008, P-4).
//!
//! # Format
//!
//! Little-endian throughout. A file header (`magic`, `universe`, and for the v29
//! format a string-table offset), then a run of app sections terminated by an
//! appid of zero. Each section: `appid`, `size` (the frame), then within the
//! frame the section header (`info_state`, `last_updated`, `pics_token`, a text
//! VDF sha1, `change_number`, and for v28 and later a binary VDF sha1) followed by
//! the binary key-values blob. In the v29 format the key of each key-values node
//! is a u32 index into the string table rather than an inline string; string
//! values stay inline in every version.
//!
//! # Honest limitation
//!
//! A hand-transcribed binary layout can be self-consistent with a synthetic
//! fixture yet wrong against a real file, the same offset trap slice S09 recorded
//! for the pcap header. This parser is validated offline against generated bytes;
//! validation against a real `appinfo.vdf` on a machine with Steam installed is a
//! manual step, like live capture. The size-framing bounds the damage: a drifted
//! inner parse fails its one section and is counted, never corrupting the read of
//! the others.

use std::path::Path;

use crate::vdf::VdfValue;
use crate::SteamError;

/// One launch entry as the cache records it, boundary-neutral.
///
/// This crate may not depend on `fragcap-targets`, so it does not reuse that
/// crate's `LaunchEntry`; the facade maps this to it field for field. Every field
/// is stored exactly as the cache holds it (P-9): no reduction, no normalization.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SteamLaunchEntry {
    /// The launch executable. Required and non-empty; the one field an entry must
    /// have to be stored.
    pub executable: String,
    /// The launch arguments, if any.
    pub arguments: Option<String>,
    /// The appinfo `type` of this launch entry (for example `default`).
    pub launch_type: Option<String>,
    /// The appinfo `config/oslist`, verbatim (for example `windows`).
    pub os: Option<String>,
    /// The appinfo `config/osarch`, verbatim.
    pub osarch: Option<String>,
    /// The appinfo `config/betakey`, verbatim.
    pub beta_branch: Option<String>,
    /// The launch entry description, if any.
    pub description: Option<String>,
}

/// One application's parsed appinfo section.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AppInfoApp {
    /// The Steam application id from the section header.
    pub appid: u32,
    /// The section's change-number; the staleness key.
    pub change_number: u32,
    /// The launch entries in cache order, verbatim.
    pub launch: Vec<SteamLaunchEntry>,
    /// The appinfo `common/type` value, verbatim (for example `Game`, `Music`,
    /// `Application`), or `None` when the section carries no `common` block or no
    /// `type` key within it. Never guessed from another field (P-9): the install-path
    /// join (slice S066) reads this rather than assuming every title is a `Game`.
    pub common_type: Option<String>,
}

/// A section (or the file header) that could not be parsed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AppInfoFailure {
    /// The section's appid when the header was readable, else `None` (a fault
    /// before an appid ends the file).
    pub appid: Option<u32>,
    /// A human-readable cause.
    pub reason: String,
}

/// The result of parsing a whole appinfo file: the apps read cleanly and the
/// sections that failed. Failures are kept, never dropped (P-4).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct AppInfoParse {
    /// Every section parsed cleanly.
    pub apps: Vec<AppInfoApp>,
    /// Sections (or the header) that could not be parsed.
    pub failures: Vec<AppInfoFailure>,
}

/// Read and parse the appinfo cache under a Steam root
/// (`root/appcache/appinfo.vdf`).
///
/// Portable (takes the root), so it is testable against a fixture tree. A missing
/// file is `Ok` with an empty parse: no appinfo cache is not an error, matching the
/// library walk's convention for a Steam that has fetched nothing. A present but
/// unreadable file is a [`SteamError::Io`]. Opens no process handle (P-1).
pub fn read_appinfo(root: &Path) -> Result<AppInfoParse, SteamError> {
    let path = root.join("appcache").join("appinfo.vdf");
    match std::fs::read(&path) {
        Ok(bytes) => Ok(parse_appinfo(&bytes)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(AppInfoParse::default()),
        Err(source) => Err(SteamError::Io { path, source }),
    }
}

/// Read the raw appinfo cache bytes under a Steam root, or `None` when the file is
/// absent.
///
/// The accumulation orchestrator uses this rather than [`read_appinfo`]: it needs
/// the bytes to construct an [`AppInfoReader`] and stream section headers, deciding
/// staleness before decoding a body. A missing file is `Ok(None)` (no cache is not
/// an error); an unreadable one is a [`SteamError::Io`]. Opens no process handle
/// (P-1).
pub fn read_appinfo_bytes(root: &Path) -> Result<Option<Vec<u8>>, SteamError> {
    let path = root.join("appcache").join("appinfo.vdf");
    match std::fs::read(&path) {
        Ok(bytes) => Ok(Some(bytes)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(SteamError::Io { path, source }),
    }
}

const MAGIC_V27: u32 = 0x0756_4427;
const MAGIC_V28: u32 = 0x0756_4428;
const MAGIC_V29: u32 = 0x0756_4429;

/// Parse raw appinfo bytes into every section decoded.
///
/// A convenience over [`AppInfoReader`], used by tests and simple consumers. The
/// accumulation orchestrator uses the reader directly instead, so it can decide
/// staleness from a section header and skip decoding an unchanged section's body.
/// An unrecognized magic yields no apps and a single header failure; a file-level
/// framing fault (a truncated tail, a size past the end) is recorded with a `None`
/// appid and stops the walk, because nothing beyond it can be trusted.
pub fn parse_appinfo(bytes: &[u8]) -> AppInfoParse {
    let mut reader = match AppInfoReader::open(bytes) {
        Ok(reader) => reader,
        Err(reason) => return header_failure(reason),
    };

    let mut apps = Vec::new();
    let mut failures = Vec::new();
    loop {
        match reader.next_section() {
            None => break, // clean terminator
            Some(Err(reason)) => {
                failures.push(AppInfoFailure {
                    appid: None,
                    reason,
                });
                break;
            }
            Some(Ok(section)) => match reader.decode(&section) {
                Ok(root) => apps.push(AppInfoApp {
                    appid: section.appid,
                    change_number: section.change_number,
                    common_type: extract_common_type(&root),
                    launch: extract_launch(&root),
                }),
                // A per-section key-values fault: the framing was intact, so the
                // walk resyncs to the next section (FR-008).
                Err(reason) => failures.push(section_failure(section.appid, reason)),
            },
        }
    }
    AppInfoParse { apps, failures }
}

fn header_failure(reason: impl Into<String>) -> AppInfoParse {
    AppInfoParse {
        apps: Vec::new(),
        failures: vec![AppInfoFailure {
            appid: None,
            reason: reason.into(),
        }],
    }
}

fn section_failure(appid: u32, reason: impl Into<String>) -> AppInfoFailure {
    AppInfoFailure {
        appid: Some(appid),
        reason: reason.into(),
    }
}

/// A cheap handle to one application's section: its identity and change-number
/// (read from the fixed section header) and the byte range of its key-values body,
/// which is decoded only on demand.
#[derive(Clone, Copy, Debug)]
pub struct SectionInfo {
    /// The Steam application id.
    pub appid: u32,
    /// The section's change-number; the staleness key.
    pub change_number: u32,
    /// The key-values body range within the reader's bytes.
    body: (usize, usize),
}

/// A streaming reader over appinfo bytes.
///
/// It reads the file header once (magic, universe, and the v29 string table) and
/// then yields one section header at a time, skipping each section's key-values
/// body by its size field. A caller decides per section, from the application id
/// and change-number, whether to decode the body ([`AppInfoReader::launch_entries`])
/// or skip it. This is what lets accumulation do near-zero work on a repeat run: an
/// unchanged section is never decoded.
pub struct AppInfoReader<'a> {
    bytes: &'a [u8],
    cursor: usize,
    has_binary_sha1: bool,
    string_table: Option<Vec<String>>,
    ended: bool,
}

impl<'a> AppInfoReader<'a> {
    /// Read the file header and prepare to stream sections. A bad magic, a
    /// truncated header, or a malformed string table is a file-level fault returned
    /// here, before any section is read.
    pub fn open(bytes: &'a [u8]) -> Result<Self, String> {
        let mut c = Cursor::new(bytes);
        let magic = c.u32().ok_or("appinfo file too short for its magic")?;
        let (has_binary_sha1, indexed_keys) = match magic {
            MAGIC_V27 => (false, false),
            MAGIC_V28 => (true, false),
            MAGIC_V29 => (true, true),
            other => return Err(format!("unrecognized appinfo magic {other:#010x}")),
        };
        c.u32().ok_or("appinfo truncated after magic")?; // universe
        let string_table = if indexed_keys {
            let offset = c
                .i64()
                .ok_or("appinfo truncated before the string-table offset")?;
            Some(read_string_table(bytes, offset)?)
        } else {
            None
        };
        Ok(AppInfoReader {
            bytes,
            cursor: c.position(),
            has_binary_sha1,
            string_table,
            ended: false,
        })
    }

    /// The next section header, or `None` at the clean terminator (an appid of
    /// zero). `Some(Err(..))` is a file-level framing fault: the section list is
    /// truncated, a size runs past the end, or a section is too short to hold its
    /// header, so nothing beyond it is trustworthy and the walk must stop.
    pub fn next_section(&mut self) -> Option<Result<SectionInfo, String>> {
        if self.ended {
            return None;
        }
        let mut c = Cursor {
            b: self.bytes,
            i: self.cursor,
        };
        let appid = match c.u32() {
            Some(a) => a,
            None => {
                self.ended = true;
                return Some(Err("appinfo ended before the terminating appid".to_string()));
            }
        };
        if appid == 0 {
            self.ended = true;
            return None; // clean end of the section list
        }
        let size = match c.u32() {
            Some(s) => s as usize,
            None => {
                self.ended = true;
                return Some(Err(format!("section {appid} truncated before its size")));
            }
        };
        let body_start = c.position();
        let section_end = match body_start.checked_add(size) {
            Some(end) if end <= self.bytes.len() => end,
            _ => {
                self.ended = true;
                return Some(Err(format!(
                    "section {appid} size exceeds the remaining bytes"
                )));
            }
        };
        // Advance past the whole section whether or not the caller decodes it.
        self.cursor = section_end;

        // The fixed section header: info_state(4) last_updated(4) pics_token(8)
        // text_sha1(20) change_number(4) [binary_sha1(20)], then the key-values body.
        let fixed = 4 + 4 + 8 + 20 + 4 + if self.has_binary_sha1 { 20 } else { 0 };
        if size < fixed {
            self.ended = true;
            return Some(Err(format!("section {appid} too short for its header")));
        }
        let cn_at = body_start + 4 + 4 + 8 + 20;
        let cn = &self.bytes[cn_at..cn_at + 4];
        let change_number = u32::from_le_bytes([cn[0], cn[1], cn[2], cn[3]]);
        Some(Ok(SectionInfo {
            appid,
            change_number,
            body: (body_start + fixed, section_end),
        }))
    }

    /// Decode one section's key-values body into its parsed tree, on demand. A
    /// malformed body is a per-section error the caller counts as a failed
    /// application; it does not stop the walk. Shared by every per-section
    /// extraction ([`launch_entries`](Self::launch_entries), and
    /// [`extract_common_type`]) so a section is decoded once regardless of how many
    /// facts are read out of it.
    pub fn decode(&self, section: &SectionInfo) -> Result<VdfValue, String> {
        let body = &self.bytes[section.body.0..section.body.1];
        let mut c = Cursor::new(body);
        let members = parse_kv_members(&mut c, self.string_table.as_deref(), true)?;
        Ok(VdfValue::Obj(members))
    }

    /// Decode one section's launch entries, on demand. A malformed key-values body
    /// is a per-section error the caller counts as a failed application; it does not
    /// stop the walk.
    pub fn launch_entries(&self, section: &SectionInfo) -> Result<Vec<SteamLaunchEntry>, String> {
        self.decode(section).map(|root| extract_launch(&root))
    }
}

/// Read the v29 string table at an absolute offset: a u32 count then that many
/// NUL-terminated strings.
fn read_string_table(bytes: &[u8], offset: i64) -> Result<Vec<String>, String> {
    if offset < 0 || offset as usize > bytes.len() {
        return Err("string-table offset out of range".to_string());
    }
    let mut c = Cursor {
        b: bytes,
        i: offset as usize,
    };
    let count =
        c.u32()
            .ok_or_else(|| "string table truncated before its count".to_string())? as usize;
    let mut out = Vec::with_capacity(count.min(bytes.len()));
    for _ in 0..count {
        let s = c
            .cstr()
            .ok_or_else(|| "string table truncated inside a string".to_string())?;
        out.push(s);
    }
    Ok(out)
}

/// Parse a run of binary key-values nodes until an end marker (`0x08`), or, at the
/// root of a section's data (`top`), the end of the input.
fn parse_kv_members(
    c: &mut Cursor<'_>,
    table: Option<&[String]>,
    top: bool,
) -> Result<Vec<(String, VdfValue)>, String> {
    let mut out = Vec::new();
    loop {
        let node_type = match c.u8() {
            Some(t) => t,
            // End of input. Legitimate only at the root of a section's data; inside
            // a nested object it means the section was truncated before its closing
            // marker, so the observation is partial and must fail rather than be
            // stored as if complete (P-9).
            None => {
                if top {
                    return Ok(out);
                }
                return Err("truncated before an object's end marker".to_string());
            }
        };
        match node_type {
            0x08 => return Ok(out), // end of this object
            0x00 => {
                let key = read_key(c, table)?;
                let members = parse_kv_members(c, table, false)?;
                out.push((key, VdfValue::Obj(members)));
            }
            0x01 => {
                let key = read_key(c, table)?;
                let value = c.cstr().ok_or("truncated string value")?;
                out.push((key, VdfValue::Str(value)));
            }
            // Numeric leaves. We do not navigate these, but we must consume their
            // fixed width to keep parsing the sibling keys we do read; store a
            // decimal string so the tree stays faithful.
            0x02 | 0x04 | 0x06 => {
                let key = read_key(c, table)?;
                let n = c.u32().ok_or("truncated 32-bit value")?;
                out.push((key, VdfValue::Str(n.to_string())));
            }
            0x07 | 0x0A => {
                let key = read_key(c, table)?;
                let n = c.u64().ok_or("truncated 64-bit value")?;
                out.push((key, VdfValue::Str(n.to_string())));
            }
            0x03 => {
                let key = read_key(c, table)?;
                let n = c.u32().ok_or("truncated float value")?;
                out.push((key, VdfValue::Str(f32::from_bits(n).to_string())));
            }
            0x05 => {
                let key = read_key(c, table)?;
                let value = c.wstr().ok_or("truncated wide string value")?;
                out.push((key, VdfValue::Str(value)));
            }
            other => return Err(format!("unknown binary key-values type {other:#04x}")),
        }
    }
}

/// Read a node key: an inline NUL-terminated string, or a u32 index into the v29
/// string table.
fn read_key(c: &mut Cursor<'_>, table: Option<&[String]>) -> Result<String, String> {
    match table {
        Some(strings) => {
            let idx = c.u32().ok_or("truncated key index")? as usize;
            strings
                .get(idx)
                .cloned()
                .ok_or_else(|| format!("key index {idx} out of range"))
        }
        None => c.cstr().ok_or_else(|| "truncated key".to_string()),
    }
}

/// Extract the launch entries from an app's parsed tree.
///
/// The tree's root is the app's data, whose single child is the appid-keyed
/// object; `config/launch` lives inside that. We accept `config` on the root or on
/// its immediate object child, so a wrapper level does not matter. Every entry is
/// stored verbatim; an entry with no executable yields nothing (P-9, FR-005,
/// FR-009).
fn extract_launch(root: &VdfValue) -> Vec<SteamLaunchEntry> {
    let Some(config) = find_config(root) else {
        return Vec::new();
    };
    let Some(launch) = config.get("launch").and_then(VdfValue::entries) else {
        return Vec::new();
    };

    let mut out = Vec::new();
    for (_index, entry) in launch {
        let Some(executable) = entry
            .get("executable")
            .and_then(VdfValue::as_str)
            .filter(|s| !s.is_empty())
        else {
            continue; // an executable is the one required field
        };
        let entry_config = entry.get("config");
        out.push(SteamLaunchEntry {
            executable: executable.to_string(),
            arguments: owned(entry.get("arguments")),
            launch_type: owned(entry.get("type")),
            os: owned(entry_config.and_then(|c| c.get("oslist"))),
            osarch: owned(entry_config.and_then(|c| c.get("osarch"))),
            beta_branch: owned(entry_config.and_then(|c| c.get("betakey"))),
            description: owned(entry.get("description")),
        });
    }
    out
}

/// Find the `config` object on the root or on its immediate object child (the
/// appid wrapper).
fn find_config(root: &VdfValue) -> Option<&VdfValue> {
    if let Some(config) = root.get("config") {
        return Some(config);
    }
    for (_key, value) in root.entries()? {
        if let Some(config) = value.get("config") {
            return Some(config);
        }
    }
    None
}

/// Find the `common` object on the root or on its immediate object child, the same
/// wrapper-tolerant shape [`find_config`] already accepts.
fn find_common(root: &VdfValue) -> Option<&VdfValue> {
    if let Some(common) = root.get("common") {
        return Some(common);
    }
    for (_key, value) in root.entries()? {
        if let Some(common) = value.get("common") {
            return Some(common);
        }
    }
    None
}

/// Extract the appinfo `common/type` value, verbatim, from an app's parsed tree.
/// `None` when there is no `common` block or it carries no `type` key; the caller
/// never treats that as a claim about the app's type (P-9), only as "unknown".
fn extract_common_type(root: &VdfValue) -> Option<String> {
    find_common(root)?
        .get("type")
        .and_then(VdfValue::as_str)
        .map(str::to_string)
}

/// A present string value as an owned string; `None` when absent or not a string.
fn owned(value: Option<&VdfValue>) -> Option<String> {
    value.and_then(VdfValue::as_str).map(str::to_string)
}

/// A little-endian cursor over a byte slice. Every read is bounds-checked and
/// returns `None`/`Err` rather than panicking, so a truncated file is a reported
/// failure, never a crash.
struct Cursor<'a> {
    b: &'a [u8],
    i: usize,
}

impl<'a> Cursor<'a> {
    fn new(b: &'a [u8]) -> Self {
        Cursor { b, i: 0 }
    }

    fn u8(&mut self) -> Option<u8> {
        let v = *self.b.get(self.i)?;
        self.i += 1;
        Some(v)
    }

    fn u32(&mut self) -> Option<u32> {
        let end = self.i.checked_add(4)?;
        let s = self.b.get(self.i..end)?;
        self.i = end;
        Some(u32::from_le_bytes(s.try_into().ok()?))
    }

    fn u64(&mut self) -> Option<u64> {
        let end = self.i.checked_add(8)?;
        let s = self.b.get(self.i..end)?;
        self.i = end;
        Some(u64::from_le_bytes(s.try_into().ok()?))
    }

    fn i64(&mut self) -> Option<i64> {
        self.u64().map(|v| v as i64)
    }

    /// The current byte offset into the input.
    fn position(&self) -> usize {
        self.i
    }

    /// Read a NUL-terminated UTF-8 string (lossy). `None` if no terminator is
    /// found before the end of the input.
    fn cstr(&mut self) -> Option<String> {
        let start = self.i;
        while self.i < self.b.len() && self.b[self.i] != 0 {
            self.i += 1;
        }
        if self.i >= self.b.len() {
            return None; // unterminated
        }
        let s = String::from_utf8_lossy(&self.b[start..self.i]).into_owned();
        self.i += 1; // consume the NUL
        Some(s)
    }

    /// Read a NUL-terminated UTF-16LE string (lossy).
    fn wstr(&mut self) -> Option<String> {
        let mut units = Vec::new();
        loop {
            let lo = *self.b.get(self.i)?;
            let hi = *self.b.get(self.i + 1)?;
            self.i += 2;
            let u = u16::from_le_bytes([lo, hi]);
            if u == 0 {
                break;
            }
            units.push(u);
        }
        Some(String::from_utf16_lossy(&units))
    }
}

/// A synthetic appinfo byte generator, shared by this crate's own tests and the
/// facade's end-to-end tests (which enable the `test-support` feature). It is the
/// single readable encoder of the format the parser reads, so the two cannot
/// drift. Excluded from normal builds.
#[cfg(any(test, feature = "test-support"))]
pub mod fixtures {
    /// The v28 format: inline string keys, with a binary sha1 field.
    pub const V28: u32 = super::MAGIC_V28;
    /// The v29 format: string-table (indexed) keys.
    pub const V29: u32 = super::MAGIC_V29;

    /// One launch entry to encode.
    #[derive(Clone, Debug, Default)]
    pub struct FixtureLaunch {
        pub executable: String,
        pub launch_type: Option<String>,
        pub arguments: Option<String>,
        pub os: Option<String>,
        pub osarch: Option<String>,
        pub beta_branch: Option<String>,
    }

    impl FixtureLaunch {
        /// A Windows launch entry with just an executable and `oslist windows`.
        pub fn windows(executable: &str) -> Self {
            FixtureLaunch {
                executable: executable.to_string(),
                launch_type: Some("default".to_string()),
                os: Some("windows".to_string()),
                ..Default::default()
            }
        }
    }

    /// One application to encode.
    #[derive(Clone, Debug)]
    pub struct FixtureApp {
        pub appid: u32,
        pub change_number: u32,
        pub launch: Vec<FixtureLaunch>,
        /// The `common/type` value to encode, or `None` to omit the key entirely
        /// (distinct from an empty string).
        pub common_type: Option<String>,
    }

    /// Which section, if any, to corrupt, and how.
    enum Bad {
        None,
        /// A valid size frame but a single unknown key-values type byte.
        UnknownType(usize),
        /// A valid size frame but a body truncated inside nested objects (config,
        /// launch, and an entry are opened and an executable written, with no
        /// closing markers), so the section is a per-section parse failure rather
        /// than a silently-partial entry.
        TruncatedKv(usize),
    }

    /// Build a valid appinfo file for the given apps in the given format version.
    pub fn appinfo_bytes(version: u32, apps: &[FixtureApp]) -> Vec<u8> {
        build(version, apps, Bad::None)
    }

    /// Build an appinfo file where the section at `bad_index` carries a valid
    /// size frame but a malformed key-values blob (a single unknown type byte), so
    /// the parser fails that one section and resyncs to the next.
    pub fn appinfo_bytes_with_bad_section(
        version: u32,
        apps: &[FixtureApp],
        bad_index: usize,
    ) -> Vec<u8> {
        build(version, apps, Bad::UnknownType(bad_index))
    }

    /// Build an appinfo file where the section at `bad_index` has valid framing but
    /// a key-values body truncated inside nested objects.
    pub fn appinfo_bytes_with_truncated_kv(
        version: u32,
        apps: &[FixtureApp],
        bad_index: usize,
    ) -> Vec<u8> {
        build(version, apps, Bad::TruncatedKv(bad_index))
    }

    enum Node {
        Obj(Vec<(String, Node)>),
        Str(String),
        U64(u64),
    }

    #[derive(Default)]
    struct StringTable {
        strings: Vec<String>,
    }

    impl StringTable {
        fn intern(&mut self, key: &str) -> u32 {
            if let Some(i) = self.strings.iter().position(|s| s == key) {
                return i as u32;
            }
            self.strings.push(key.to_string());
            (self.strings.len() - 1) as u32
        }
    }

    fn build(version: u32, apps: &[FixtureApp], bad: Bad) -> Vec<u8> {
        let indexed = version == V29;
        let has_binary_sha1 = version >= V28;
        let mut table = if indexed {
            Some(StringTable::default())
        } else {
            None
        };

        let mut sections = Vec::new();
        for (i, app) in apps.iter().enumerate() {
            let data = match bad {
                Bad::UnknownType(idx) if idx == i => vec![0xFFu8], // an unknown type byte
                Bad::TruncatedKv(idx) if idx == i => truncated_kv_body(&mut table),
                _ => {
                    let mut buf = Vec::new();
                    write_node(&mut buf, &app.appid.to_string(), &app_node(app), &mut table);
                    buf
                }
            };

            let mut body = Vec::new();
            body.extend_from_slice(&0u32.to_le_bytes()); // info_state
            body.extend_from_slice(&0u32.to_le_bytes()); // last_updated
            body.extend_from_slice(&0u64.to_le_bytes()); // pics_token
            body.extend_from_slice(&[0u8; 20]); // text sha1
            body.extend_from_slice(&app.change_number.to_le_bytes());
            if has_binary_sha1 {
                body.extend_from_slice(&[0u8; 20]); // binary sha1
            }
            body.extend_from_slice(&data);

            sections.extend_from_slice(&app.appid.to_le_bytes());
            sections.extend_from_slice(&(body.len() as u32).to_le_bytes());
            sections.extend_from_slice(&body);
        }

        let mut out = Vec::new();
        out.extend_from_slice(&version.to_le_bytes());
        out.extend_from_slice(&1u32.to_le_bytes()); // universe
        if let Some(table) = table {
            let header_len = 4 + 4 + 8;
            let offset = header_len + sections.len() + 4; // + the 4-byte terminator
            out.extend_from_slice(&(offset as i64).to_le_bytes());
            out.extend_from_slice(&sections);
            out.extend_from_slice(&0u32.to_le_bytes()); // terminator
            out.extend_from_slice(&(table.strings.len() as u32).to_le_bytes());
            for s in &table.strings {
                out.extend_from_slice(s.as_bytes());
                out.push(0);
            }
        } else {
            out.extend_from_slice(&sections);
            out.extend_from_slice(&0u32.to_le_bytes()); // terminator
        }
        out
    }

    fn app_node(app: &FixtureApp) -> Node {
        let mut launch = Vec::new();
        for (i, l) in app.launch.iter().enumerate() {
            let mut entry = vec![("executable".to_string(), Node::Str(l.executable.clone()))];
            if let Some(t) = &l.launch_type {
                entry.push(("type".to_string(), Node::Str(t.clone())));
            }
            if let Some(a) = &l.arguments {
                entry.push(("arguments".to_string(), Node::Str(a.clone())));
            }
            let mut cfg = Vec::new();
            if let Some(v) = &l.os {
                cfg.push(("oslist".to_string(), Node::Str(v.clone())));
            }
            if let Some(v) = &l.osarch {
                cfg.push(("osarch".to_string(), Node::Str(v.clone())));
            }
            if let Some(v) = &l.beta_branch {
                cfg.push(("betakey".to_string(), Node::Str(v.clone())));
            }
            if !cfg.is_empty() {
                entry.push(("config".to_string(), Node::Obj(cfg)));
            }
            launch.push((i.to_string(), Node::Obj(entry)));
        }
        // A common block before config, so the parser must skip a string and a
        // uint64 sibling before reaching launch.
        let mut common = vec![
            ("name".to_string(), Node::Str("Fixture Game".to_string())),
            ("gameid".to_string(), Node::U64(app.appid as u64)),
        ];
        if let Some(t) = &app.common_type {
            common.push(("type".to_string(), Node::Str(t.clone())));
        }
        Node::Obj(vec![
            ("common".to_string(), Node::Obj(common)),
            (
                "config".to_string(),
                Node::Obj(vec![("launch".to_string(), Node::Obj(launch))]),
            ),
        ])
    }

    /// A key-values body that opens `config`, `launch`, and an entry, writes an
    /// `executable` string, and then stops with no end markers: valid framing, a
    /// body truncated inside nested objects.
    fn truncated_kv_body(table: &mut Option<StringTable>) -> Vec<u8> {
        let mut buf = Vec::new();
        for key in ["config", "launch", "0"] {
            buf.push(0x00);
            write_key(&mut buf, key, table);
        }
        buf.push(0x01);
        write_key(&mut buf, "executable", table);
        buf.extend_from_slice(b"x.exe");
        buf.push(0);
        buf
    }

    fn write_node(buf: &mut Vec<u8>, key: &str, node: &Node, table: &mut Option<StringTable>) {
        match node {
            Node::Obj(children) => {
                buf.push(0x00);
                write_key(buf, key, table);
                for (k, v) in children {
                    write_node(buf, k, v, table);
                }
                buf.push(0x08);
            }
            Node::Str(s) => {
                buf.push(0x01);
                write_key(buf, key, table);
                buf.extend_from_slice(s.as_bytes());
                buf.push(0);
            }
            Node::U64(n) => {
                buf.push(0x07);
                write_key(buf, key, table);
                buf.extend_from_slice(&n.to_le_bytes());
            }
        }
    }

    fn write_key(buf: &mut Vec<u8>, key: &str, table: &mut Option<StringTable>) {
        match table {
            Some(t) => buf.extend_from_slice(&t.intern(key).to_le_bytes()),
            None => {
                buf.extend_from_slice(key.as_bytes());
                buf.push(0);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::fixtures::{
        appinfo_bytes, appinfo_bytes_with_bad_section, appinfo_bytes_with_truncated_kv, FixtureApp,
        FixtureLaunch, V28, V29,
    };
    use super::*;
    use crate::test_support::TempTree;

    fn one_windows_app(appid: u32, change: u32, exe: &str) -> FixtureApp {
        FixtureApp {
            appid,
            change_number: change,
            launch: vec![FixtureLaunch::windows(exe)],
            common_type: None,
        }
    }

    #[test]
    fn parses_a_single_windows_launch_in_both_formats() {
        for version in [V28, V29] {
            let bytes = appinfo_bytes(version, &[one_windows_app(730, 55, "cs2.exe")]);
            let parse = parse_appinfo(&bytes);
            assert!(
                parse.failures.is_empty(),
                "version {version:#x}: {:?}",
                parse.failures
            );
            assert_eq!(parse.apps.len(), 1);
            let app = &parse.apps[0];
            assert_eq!(app.appid, 730);
            assert_eq!(app.change_number, 55);
            assert_eq!(app.launch.len(), 1);
            assert_eq!(app.launch[0].executable, "cs2.exe");
            assert_eq!(app.launch[0].os.as_deref(), Some("windows"));
            assert_eq!(app.launch[0].launch_type.as_deref(), Some("default"));
        }
    }

    #[test]
    fn stores_multiple_os_filtered_entries_verbatim_and_in_order() {
        let app = FixtureApp {
            appid: 400,
            change_number: 9,
            launch: vec![
                FixtureLaunch {
                    executable: "game.exe".to_string(),
                    os: Some("windows".to_string()),
                    osarch: Some("64".to_string()),
                    ..Default::default()
                },
                FixtureLaunch {
                    executable: "game.sh".to_string(),
                    os: Some("linux".to_string()),
                    beta_branch: Some("beta".to_string()),
                    ..Default::default()
                },
            ],
            common_type: None,
        };
        let parse = parse_appinfo(&appinfo_bytes(V29, &[app]));
        assert!(parse.failures.is_empty());
        let entries = &parse.apps[0].launch;
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].executable, "game.exe");
        assert_eq!(entries[0].os.as_deref(), Some("windows"));
        assert_eq!(entries[0].osarch.as_deref(), Some("64"));
        assert_eq!(entries[1].executable, "game.sh");
        assert_eq!(entries[1].os.as_deref(), Some("linux"));
        assert_eq!(entries[1].beta_branch.as_deref(), Some("beta"));
    }

    #[test]
    fn a_malformed_middle_section_is_isolated_and_the_walk_resyncs() {
        let apps = [
            one_windows_app(1, 10, "a.exe"),
            one_windows_app(2, 20, "b.exe"),
            one_windows_app(3, 30, "c.exe"),
        ];
        let bytes = appinfo_bytes_with_bad_section(V28, &apps, 1);
        let parse = parse_appinfo(&bytes);

        // The good first and third apps parse; the middle one is a counted failure.
        let ids: Vec<u32> = parse.apps.iter().map(|a| a.appid).collect();
        assert_eq!(ids, vec![1, 3], "resynced past the bad section");
        assert_eq!(parse.failures.len(), 1);
        assert_eq!(parse.failures[0].appid, Some(2));
    }

    #[test]
    fn a_section_truncated_inside_nested_objects_is_a_failure_not_a_partial_entry() {
        // The middle section opens config/launch/entry and writes an executable but
        // never closes the objects. It must be counted as a failure, not yield a
        // launch entry from a partial observation (P-9). The framing is intact, so
        // the walk still resyncs to the third app.
        for version in [V28, V29] {
            let apps = [
                one_windows_app(1, 10, "a.exe"),
                one_windows_app(2, 20, "b.exe"),
                one_windows_app(3, 30, "c.exe"),
            ];
            let bytes = appinfo_bytes_with_truncated_kv(version, &apps, 1);
            let parse = parse_appinfo(&bytes);
            let ids: Vec<u32> = parse.apps.iter().map(|a| a.appid).collect();
            assert_eq!(
                ids,
                vec![1, 3],
                "version {version:#x}: resynced past the truncated section"
            );
            assert_eq!(parse.failures.len(), 1);
            assert_eq!(parse.failures[0].appid, Some(2));
        }
    }

    #[test]
    fn an_unrecognized_magic_is_one_failure_and_no_apps() {
        let bytes = [0xEF, 0xBE, 0xAD, 0xDE, 1, 0, 0, 0];
        let parse = parse_appinfo(&bytes);
        assert!(parse.apps.is_empty());
        assert_eq!(parse.failures.len(), 1);
        assert_eq!(parse.failures[0].appid, None);
    }

    #[test]
    fn a_truncated_file_yields_a_trailing_failure() {
        let full = appinfo_bytes(V28, &[one_windows_app(1, 1, "a.exe")]);
        // Cut inside the first section so its size exceeds the remaining bytes.
        let truncated = &full[..14];
        let parse = parse_appinfo(truncated);
        assert!(parse.apps.is_empty());
        assert!(!parse.failures.is_empty());
    }

    #[test]
    fn an_entry_with_no_executable_yields_nothing_but_is_not_a_failure() {
        let app = FixtureApp {
            appid: 5,
            change_number: 1,
            launch: vec![FixtureLaunch {
                executable: String::new(), // empty: not storable
                os: Some("windows".to_string()),
                ..Default::default()
            }],
            common_type: None,
        };
        let parse = parse_appinfo(&appinfo_bytes(V29, &[app]));
        assert!(parse.failures.is_empty());
        assert_eq!(parse.apps.len(), 1);
        assert!(parse.apps[0].launch.is_empty());
    }

    #[test]
    fn common_type_is_read_verbatim_when_present_and_none_when_absent() {
        let music = FixtureApp {
            appid: 100,
            change_number: 1,
            launch: vec![FixtureLaunch::windows("music.exe")],
            common_type: Some("Music".to_string()),
        };
        let game = FixtureApp {
            appid: 200,
            change_number: 1,
            launch: vec![FixtureLaunch::windows("game.exe")],
            common_type: Some("Game".to_string()),
        };
        let untyped = one_windows_app(300, 1, "untyped.exe");

        for version in [V28, V29] {
            let parse = parse_appinfo(&appinfo_bytes(
                version,
                &[music.clone(), game.clone(), untyped.clone()],
            ));
            assert!(parse.failures.is_empty(), "version {version:#x}");
            assert_eq!(parse.apps.len(), 3);
            assert_eq!(parse.apps[0].common_type.as_deref(), Some("Music"));
            assert_eq!(parse.apps[1].common_type.as_deref(), Some("Game"));
            assert_eq!(
                parse.apps[2].common_type, None,
                "a section with no common/type key reads as unknown, not a claim"
            );
        }
    }

    #[test]
    fn read_appinfo_missing_file_is_empty_ok() {
        let tree = TempTree::new();
        // No appcache/appinfo.vdf under the root.
        let parse = read_appinfo(tree.path()).expect("missing file is not an error");
        assert!(parse.apps.is_empty());
        assert!(parse.failures.is_empty());
    }

    #[test]
    fn read_appinfo_reads_a_present_file() {
        let tree = TempTree::new();
        let bytes = appinfo_bytes(V29, &[one_windows_app(42, 7, "forty-two.exe")]);
        tree.write_bytes(&tree.path().join("appcache").join("appinfo.vdf"), &bytes);
        let parse = read_appinfo(tree.path()).expect("read");
        assert_eq!(parse.apps.len(), 1);
        assert_eq!(parse.apps[0].appid, 42);
        assert_eq!(parse.apps[0].launch[0].executable, "forty-two.exe");
    }
}
